# Generated by Django 5.2.6 on 2025-09-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suryaa_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('short_description', models.TextField()),
            ],
        ),
    ]
