# Generated by Django 5.2.6 on 2025-09-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suryaa_app', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
