# Generated by Django 5.2.6 on 2025-09-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suryaa_app', '0004_alter_service_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
