# Generated by Django 5.2.6 on 2025-09-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suryaa_app', '0005_remove_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
