# Generated by Django 5.2.6 on 2025-10-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suryaa_app', '0008_service_created_at_service_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccontent',
            name='content_type',
            field=models.CharField(choices=[('para', 'Paragraph'), ('point', 'Point'), ('image', 'Image'), ('subtopic', 'Subtopic')], max_length=10),
        ),
    ]
