# Generated by Django 5.2.6 on 2025-10-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suryaa_app', '0010_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccontent',
            name='image_or_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
